apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pickle-backend
  labels:
    app: pickle-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: pickle.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: pickle-backend
                port:
                  number: 80


