apiVersion: v1
kind: Secret
metadata:
  name: pickle-backend-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@host:5432/dbname" # change in real env
  JWT_SECRET: "change-me" # change in real env


