apiVersion: v1
kind: Service
metadata:
  name: pickle-backend
  labels:
    app: pickle-backend
spec:
  type: ClusterIP
  selector:
    app: pickle-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000


